Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [2]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Answer:-Yes, there is a difference in the data type of variables list_ and array_list. The list_ variable is a Python list object, whereas the array_list variable is a NumPy array object. We can print the data types of both variables using the following code:

In [3]:
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Answer:-We can print the data type of each and every element of both the variables using a loop as follows:

In [4]:
# For list_
for elem in list_:
    print(type(elem))

# For array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer:-Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. When we create the array_list using the np.array function with the dtype parameter set to int, the elements of the resulting array will be converted to integers. We can print the data types of each and every element present in both the variables using the following code:

In [5]:
# For list_
for elem in list_:
    print(type(elem))

# For array_list
for elem in array_list:
    print(type(elem))

# For updated array_list
array_list = np.array(object=list_, dtype=int)
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Answer:-We can create a numpy array of a 3x3 matrix containing only zeros using the np.zeros function as follows:

In [8]:
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Answer:-We can create an identity matrix of shape (5,5) using the np.eye function as follows: